version: "3.9"

services:
  app:
    build:
      context: .
      args:
        - DEV=true
      network: host
    ports:
      - "4000:4000"
    volumes:
      - ./app:/app
    # http://127.0.0.1:4000/
    command: >
      sh -c "python manage.py runserver 0.0.0.0:4000"
      
